import Vue from 'vue'
import { Button, Dropdown, Icon, Menu, Collapse, Row, Col, Tooltip, Skeleton, Tabs, Carousel, Table, Select, Divider, Form, Input, Modal, List, Avatar } from 'ant-design-vue'

Vue.use(Dropdown)
Vue.use(Icon)
Vue.use(Menu)
Vue.use(Button)
Vue.use(Collapse)
Vue.use(Row)
Vue.use(Col)
Vue.use(Tooltip)
Vue.use(Skeleton)
Vue.use(Tabs)
Vue.use(Carousel)
Vue.use(Table)
Vue.use(Select)
Vue.use(Divider)
Vue.use(Form)
Vue.use(Input)
Vue.use(Modal)
Vue.use(List)
Vue.use(Avatar)
